---
- hosts: all
  roles:
  - role: system

  - role: server/mount_drives

  - role: programming

  - role: geerlingguy.pip
    become: True

  - role: geerlingguy.docker
    become: True

  - role: server/folders
    become: True

  - role: server/containers
    become: True
