- name: Create personal_repos folder
  file:
    path: "~/dev/personal_repos"
    state: directory

- name: Clone bash scripts
  ansible.builtin.git:
    repo: "https://github.com/DylanRitchings/bash_scripts.git"
    dest: "~/dev/personal_repos"

- name: Copy .zshrc.j2 template to home directory
  template:
    src: ../templates/.zshrc.j2
    dest: "{{ ansible_env.HOME }}/.zshrc"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Add source line to .bashrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "{{ pointers.aliases }}"
    state: present

- name: Install zsh and plugins
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - zsh
    - fzf
    - zsh-syntax-highlighting

- name: change user shell to zsh
  user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh

- name: Check if Oh My Zsh directory exists
  stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: ohmyzsh_dir

- name: Run Oh My Zsh installation script
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh) && exit"
  when: not ohmyzsh_dir.stat.exists

- name: Clone zsh plugins
  ansible.builtin.git:
    repo: "https://github.com/Aloxaf/fzf-tab"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/plugins/fzf-tab"
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/plugins/fzf-tab"
  ansible.builtin.git:
    repo: "https://github.com/z-shell/F-Sy-H.git"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/plugins/F-Sy-H"
