- name: Update packages
  become: yes
  apt:
    update_cache: yes
    upgrade: yes

- name: Install essential packages
  include_tasks: roles/common/install_packages.yml
  vars:
    packages: "{{ essential_packages }}"
