- name: Create folders

  var: folders

  file:
    path: "{{ parent + '/' + item }}"
    state: directory
  loop: "{{ subfolders }}"
  vars:
    parent: "{{ folders.parent }}"
    subfolders: "{{ folders.subfolders }}"
